version: '3'
services:
  youtrack:
    image: jetbrains/youtrack:2024.1.26888
    container_name: youtrack
    restart: unless-stopped
    volumes:
      - /opt/services/data:/opt/youtrack/data
      - /opt/services/youtrack-conf:/opt/youtrack/conf
      - /opt/services/logs:/opt/youtrack/logs
      - /opt/services/backups:/opt/youtrack/backups
    ports:
      - '8080:8080'
      - '443:443'
    networks:
      - services_net

networks:
  services_net:
    driver: bridge
